services:
  - type: web
    name: attendsmart-api
    env: python
    buildCommand: "echo 'No dependencies to install!'"
    startCommand: "python3 server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
